# Generated by Django 4.2.3 on 2023-07-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_fotografias_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografias",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
    ]
