# Generated by Django 4.2.3 on 2023-07-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0007_alter_fotografias_publicada"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografias", old_name="decricao", new_name="descricao",
        ),
    ]
